name: "INS MyHome Control"
version: "0.1.1"
slug: "ins_myhome_control"
description: "Private Home Assistant control center for climate, energy and home automation"
url: "https://github.com/Mangid/ins-myhome-control"
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
hassio_role: default
options:
  shadow_mode: true
schema:
  shadow_mode: bool
